feat: add unit-tests to the button
aiipo/shakal pull request #3
Opened 2021-04-16 17:37 UTC by EndeZz

2021-04-16 18:14 UTC, aiipo requested changes

2021-04-16 18:14 UTC, aiipo commented on src/components/button/button.test.jsx
> +  it("children not null", () => {
Тест дублируется

2021-04-16 18:14 UTC, aiipo commented on src/components/button/button.test.jsx
> +  it("should be have property", () => {
Что этот тест вообще должен делать? Проверять в объекте значение, которое нигде не используется? 😄

2021-04-16 18:14 UTC, aiipo commented on src/components/button/button.test.jsx
> +    render(<Button disabled={prop} />);
`disabled` ожидает `boolean` значение, а не функцию

2021-04-16 18:14 UTC, aiipo commented on src/components/button/button.test.jsx
> +  it("onClick not null", () => {
Это уже проверено тем, что это функция была вызвана `expect(func).toHaveBeenCalledTimes(1);` (10 строка)

2021-04-16 18:14 UTC, aiipo commented on src/components/button/button.test.jsx
> +    render(<Button type={prop} />);
у кнопки есть разные типы: `button`, `submit` и `reset`, они строковые(а не функция). По умолчанию значение `submit`. Кнопка имеет итак какой-то тип.

2021-04-16 18:14 UTC, aiipo commented on src/components/button/button.test.jsx
> +    render(<Button disabled={prop} />);
`disabled` - boolean, а не функция. Можно добавить функцию на метод `onClick` и установить `disabled={false}` и проверить, чтобы функция не вызывалась

2021-04-16 18:14 UTC, aiipo commented on src/components/button/button.test.jsx
> +    expect(screen.getByText(child)).toBeTruthy();
есть метод `.toBeInTheDocument()`: используй его вместо `.toBeTruthy()`

2021-04-16 18:26 UTC, EndeZz commented on src/components/button/button.test.jsx
> +    const prop = jest.fn();
Планировалось - что идет проверка что в className приходит ли хоть что нибудь

2021-04-16 18:27 UTC, EndeZz commented on src/components/button/button.test.jsx
> +describe("Property not null", () => {
Т.е. имеешь ввиду что "should be have property" перенести?

2021-04-16 18:30 UTC, EndeZz commented on src/components/button/button.test.jsx
> +  it("should be have property", () => {
Типа просто пришли какие нибудь значения - и он сопоставляет их с помощью метода .toHaveProperty()
От него отказаться?

2021-04-16 18:39 UTC, aiipo commented on src/components/button/button.test.jsx
> +  it("should be have property", () => {
ты ничего в компонент не пробрасываешь

2021-04-16 18:40 UTC, EndeZz commented on src/components/button/button.test.jsx
> +    render(<Button disabled={prop} />);
Я не нашел как объявить свойство как boolean

2021-04-16 18:40 UTC, aiipo commented on src/components/button/button.test.jsx
> +describe("Property not null", () => {
Один блок `describe`, у тебя их два для одного компонента кнопки
`describe('<Button />', () => {
  it('', () => {});

  it('', () => {});
})'

2021-04-16 18:42 UTC, EndeZz commented on src/components/button/button.test.jsx
> +describe("Property not null", () => {
Я разделил их на подзадачи, первый блок собирает в себе большинство проверок, 2 - проверяет на not null

2021-04-16 18:47 UTC, aiipo commented on src/components/button/button.test.jsx
> +    const prop = jest.fn();
ну ок. Делай.

2021-04-16 18:54 UTC, aiipo commented on src/components/button/button.test.jsx
> +describe("Property not null", () => {
Описывай в одном блоке для компонента различные случаи, в т.ч. not null

2021-04-16 18:59 UTC, aiipo commented on src/components/button/button.test.jsx
> +    render(<Button disabled={prop} />);
![image](https://user-images.githubusercontent.com/53421644/115071552-70bdb380-9f07-11eb-9f86-a916c9cec40a.png)

2021-04-16 19:00 UTC, aiipo commented on src/components/button/button.test.jsx
> +    render(<Button disabled={prop} />);
`disabled={true}`
![image](https://user-images.githubusercontent.com/53421644/115071655-93e86300-9f07-11eb-9b31-97da595eca39.png)

2021-04-16 19:52 UTC, aiipo requested changes

2021-04-16 19:52 UTC, aiipo commented on src/components/button/button.test.jsx
> +    expect(prop).toContain("button");
тебе нужно проверять у компонента, а не у `prop`(и prop лучше переименовать в `type`). Нужно найти компонент и проверять у него то или иное свойство. Исправь везде

2021-04-16 19:52 UTC, aiipo commented on src/components/button/button.test.jsx
>    it("disabled contains property", () => {
не соответствует название того, что проверяешь тому, на что на самом деле проверяешь

2021-04-16 19:52 UTC, aiipo commented on src/components/button/button.test.jsx
> +    expect(prop).toBeTruthy();
Во-первых, название класса пустая строка!? Ты на это хотел проверить, на пустой класс(чем и является пробел)!?
Во-вторых, опять же проверяешь не у компонента `<Button />`, а у переменной `prop`
В-третьих, переменную `prop` переименуй в `className`

2021-04-16 19:52 UTC, aiipo commented on src/components/button/button.test.jsx
> +    render(<Button className={prop} />);
Не передавай в качестве `className` функцию! `className` - строка

2021-05-21 14:49 UTC, aiipo requested changes

2021-05-21 14:49 UTC, aiipo commented on src/components/button/button.test.jsx
> +  });
фигня какая-то

2021-05-21 14:49 UTC, aiipo commented on src/components/button/button.test.jsx
> +  it("should contains 'word' in className", () => {
не очень тест: ты пробрасываешь название класса и проверять есть ли оно. Ну такое себе..

2021-05-21 14:49 UTC, aiipo commented on src/components/button/button.test.jsx
> +    expect(func.mock.calls.length).toBe(1);
уже проверял выше с помощью `toHaveBeenCalledTimes(1)`. Вариант написанный здесь с использованием `func.mock.calls.length` не очень, лучше с `toHaveBeenCalledTimes`

2021-05-21 14:49 UTC, aiipo commented on src/components/result-preview/result-preview.test.jsx
> +    expect(elements.length).toBe(3);
У тебя есть массив `elements`, поэтому используй его длину `elements.length`, а не 3

2021-05-21 14:49 UTC, aiipo commented on src/components/result-preview/result-preview.test.jsx
> +          <ul ref={ref}/>
`ResultPreview` не принимает `children` (в твоем случае это `<ul ref={ref}/>`)

2021-05-21 14:49 UTC, aiipo commented on src/components/result-preview/result-preview.test.jsx
> +  it("should contains 'result' in className", () => {
Не нужный тест: проверяешь на название класса, которое передаешь

2021-05-21 15:04 UTC, EndeZz commented on src/components/button/button.test.jsx
> +  });
Так по названию же понятно что делает

2021-05-21 15:14 UTC, EndeZz commented on src/components/result-preview/result-preview.test.jsx
> +    expect(elements.length).toBe(3);
Имеешь ввиду: `expect(elements.length).toBe(elements.length);`? Тест срабатывает, но выглядит не оч как то.

2021-05-21 15:15 UTC, EndeZz commented on src/components/result-preview/result-preview.test.jsx
> +          <ul ref={ref}/>
А как тогда предлагаешь сделать?)

2021-05-21 15:58 UTC, EndeZz commented on src/components/button/button.test.jsx
> +  it("should contains 'word' in className", () => {
Так в этом же и смысл теста. Приходит ли название класса

2021-05-21 19:27 UTC, aiipo commented on src/components/result-preview/result-preview.test.jsx
> +    expect(elements.length).toBe(3);
Посмотрел не внимательно. Ты проверяешь `3 === 3`, а не кол-во элементов в <ResultPreview />

2021-05-22 07:27 UTC, merged